version: '3.5'

services:
  server:
    container_name: gin-quickstart
    image: gin-quickstart:v1.4.5
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
      - ./uploads:/app/uploads
    ports:
      - "8080:8080"