// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/demo": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "修改Demo",
                "parameters": [
                    {
                        "description": "修改Demo",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Demo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "创建Demo",
                "parameters": [
                    {
                        "description": "创建Demo",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Demo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "删除Demo",
                "parameters": [
                    {
                        "description": "删除Demo",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Demo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/demo/delete-batch": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "批量删除Demo",
                "parameters": [
                    {
                        "description": "批量删除Demo",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/demo/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "查询Demo列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主键",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/demo/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "查询Demo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询Demo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "查询File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "查询File",
                        "name": "fileMd5",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "修改File",
                "parameters": [
                    {
                        "description": "修改File",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "创建File",
                "parameters": [
                    {
                        "description": "创建File",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "删除File",
                "parameters": [
                    {
                        "description": "删除File",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/chunkid": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "获取分块文件id",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/delete-batch": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "批量删除File",
                "parameters": [
                    {
                        "description": "批量删除File",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "查询File列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "已经上传的分片",
                        "name": "alreadyChunk",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件MD5",
                        "name": "fileMd5",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "fileName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "filePath",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件大小",
                        "name": "fileSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "文件唯一标识",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "当前分片",
                        "name": "index",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否完成",
                        "name": "isFinish",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "文件总分片数",
                        "name": "totalChunk",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/merge-chunk": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "合并分片文件",
                "parameters": [
                    {
                        "description": "合并分片文件",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "普通上传File",
                "parameters": [
                    {
                        "type": "file",
                        "description": "普通上传File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/file/upload-chunk": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "分片上传File",
                "parameters": [
                    {
                        "type": "file",
                        "description": "分片上传File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysApi": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "修改SysApi",
                "parameters": [
                    {
                        "description": "修改SysApi",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "创建SysApi",
                "parameters": [
                    {
                        "description": "创建SysApi",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "删除SysApi",
                "parameters": [
                    {
                        "description": "删除SysApi",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysApi/delete-batch": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "批量删除SysApi",
                "parameters": [
                    {
                        "description": "批量删除SysApi",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysApi/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "查询SysApi列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysApi/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysApi"
                ],
                "summary": "查询SysApi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询SysApi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysCasbin": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "修改SysCasbin",
                "parameters": [
                    {
                        "description": "修改SysCasbin",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysCasbin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "设置角色权限",
                "parameters": [
                    {
                        "description": "创建SysCasbin",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RolePermissionsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "删除SysCasbin",
                "parameters": [
                    {
                        "description": "删除SysCasbin",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysCasbin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysCasbin/delete-batch": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "批量删除SysCasbin",
                "parameters": [
                    {
                        "description": "批量删除SysCasbin",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysCasbin/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "查询SysCasbin列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysCasbin/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysCasbin"
                ],
                "summary": "查询SysCasbin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询SysCasbin",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysMenu": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "修改SysMenu",
                "parameters": [
                    {
                        "description": "修改SysMenu",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysMenu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "创建SysMenu",
                "parameters": [
                    {
                        "description": "创建SysMenu",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysMenu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "删除SysMenu",
                "parameters": [
                    {
                        "description": "删除SysMenu",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysMenu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysMenu/delete-batch": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "批量删除SysMenu",
                "parameters": [
                    {
                        "description": "批量删除SysMenu",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysMenu/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "查询SysMenu列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "图标",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "菜单名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "上层菜单",
                        "name": "parent_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysMenu/role-list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "查询当前角色菜单列表",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "设置角色菜单列表",
                "parameters": [
                    {
                        "description": "设置角色菜单列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysMenu/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysMenu"
                ],
                "summary": "查询SysMenu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询SysMenu",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysRole": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "修改SysRole",
                "parameters": [
                    {
                        "description": "修改SysRole",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "创建SysRole",
                "parameters": [
                    {
                        "description": "创建SysRole",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "删除SysRole",
                "parameters": [
                    {
                        "description": "删除SysRole",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysRole/delete-batch": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "批量删除SysRole",
                "parameters": [
                    {
                        "description": "批量删除SysRole",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysRole/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "查询SysRole列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主键",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "role_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysRole/user-list": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "设置用户角色列表",
                "parameters": [
                    {
                        "description": "设置用户角色列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysRole/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysRole"
                ],
                "summary": "查询SysRole",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询SysRole",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "修改SysUser",
                "parameters": [
                    {
                        "description": "修改SysUser",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "创建SysUser",
                "parameters": [
                    {
                        "description": "创建SysUser",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "删除SysUser",
                "parameters": [
                    {
                        "description": "删除SysUser",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SysUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser/delete-batch": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "批量删除SysUser",
                "parameters": [
                    {
                        "description": "批量删除SysUser",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Ids"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "用户信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "查询SysUser列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "当前角色",
                        "name": "default_role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "昵称",
                        "name": "nick_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "SysUser登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"登录成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sysUser/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SysUser"
                ],
                "summary": "查询SysUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "查询SysUser",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"查询成功\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/init": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "系统初始化",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"\",\"data\":{}\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Demo": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "主键",
                    "type": "integer"
                }
            }
        },
        "domain.File": {
            "type": "object",
            "properties": {
                "alreadyChunk": {
                    "description": "已经上传的分片",
                    "type": "string"
                },
                "fileMd5": {
                    "description": "文件MD5",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "filePath": {
                    "description": "文件路径",
                    "type": "string"
                },
                "fileSize": {
                    "description": "文件大小",
                    "type": "string"
                },
                "id": {
                    "description": "文件唯一标识",
                    "type": "integer"
                },
                "index": {
                    "description": "当前分片",
                    "type": "integer"
                },
                "isFinish": {
                    "description": "是否完成",
                    "type": "boolean"
                },
                "totalChunk": {
                    "description": "文件总分片数",
                    "type": "integer"
                }
            }
        },
        "domain.LoginReq": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "domain.RolePermissionsReq": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "role": {
                    "type": "integer"
                }
            }
        },
        "domain.SysApi": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "domain.SysCasbin": {
            "type": "object"
        },
        "domain.SysMenu": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SysMenu"
                    }
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "icon": {
                    "description": "图标",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "上层菜单",
                    "type": "integer"
                }
            }
        },
        "domain.SysRole": {
            "type": "object",
            "properties": {
                "children": {
                    "description": "角色列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SysRole"
                    }
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "menus": {
                    "description": "菜单列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SysMenu"
                    }
                },
                "parent_id": {
                    "type": "integer"
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "domain.SysUser": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "default_role": {
                    "description": "当前角色",
                    "type": "integer"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "nick_name": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "roles": {
                    "description": "角色列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SysRole"
                    }
                }
            }
        },
        "request.Ids": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "id切片",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample Server pets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
